# TESTING THE MODEL

In [1]:
import pickle

# Loading  pickle files

In [2]:
#loading toxic
with open('saved_pickle_files/toxic_model.pkl', 'rb') as f:
    load_toxic = pickle.load(f)

In [3]:
load_toxic

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [4]:
with open('saved_pickle_files/toxic_vect.pkl', 'rb') as f:
    load_toxic_vect = pickle.load(f)

In [5]:
load_toxic_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [6]:
#loading severe_toxic
with open('saved_pickle_files/severe_toxic_model.pkl', 'rb') as f:
    load_severe_toxic = pickle.load(f)

In [7]:
load_severe_toxic

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [8]:
with open('saved_pickle_files/severe_toxic_vect.pkl', 'rb') as f:
    load_severe_toxic_vect = pickle.load(f)

In [9]:
load_severe_toxic_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [10]:
# loading obscene
with open('saved_pickle_files/obscene_model.pkl', 'rb') as f:
    load_obscene = pickle.load(f)

In [11]:
load_obscene

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [12]:
with open('saved_pickle_files/obscene_vect.pkl', 'rb') as f:
    load_obscene_vect = pickle.load(f)

In [13]:
load_obscene_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [14]:
#loading threat
with open('saved_pickle_files/threat_model.pkl', 'rb') as f:
    load_threat = pickle.load(f)

In [15]:
load_threat

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [16]:

with open('saved_pickle_files/threat_vect.pkl', 'rb') as f:
    load_threat_vect = pickle.load(f)
    

In [17]:
load_threat_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [18]:
#loading insult
with open('saved_pickle_files/insult_model.pkl', 'rb') as f:
    load_insult = pickle.load(f)

In [19]:
load_insult

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [20]:
with open('saved_pickle_files/insult_vect.pkl', 'rb') as f:
    load_insult_vect = pickle.load(f)
    

In [21]:
load_insult_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [22]:
# loading identity hate
with open('saved_pickle_files/identity_hate_model.pkl', 'rb') as f:
    load_identity_hate = pickle.load(f)
    

In [23]:
load_identity_hate

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [24]:
with open('saved_pickle_files/identity_hate_vect.pkl', 'rb') as f:
    load_identity_hate_vect = pickle.load(f)

In [25]:
load_identity_hate_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

# Testing by passing custom text

In [26]:
comment1 = ['I wil kill her']
comment2 = ['You are looking beautiful']



# For toxic

In [27]:
comment1_vect = load_toxic_vect.transform(comment1)
load_toxic.predict_proba(comment1_vect)[:,1]

array([0.992])

In [28]:
comment2_vect = load_toxic_vect.transform(comment2)
load_toxic.predict_proba(comment2_vect)[:,1]

array([0.24324621])

# For severe toxic

In [29]:
comment1_vect = load_severe_toxic_vect.transform(comment1)
load_severe_toxic.predict_proba(comment1_vect)[:,1]

array([0.79928571])

In [30]:
comment2_vect = load_severe_toxic_vect.transform(comment2)
load_severe_toxic.predict_proba(comment2_vect)[:,1]

array([0.3365119])

# For obscene

In [31]:
comment1_vect = load_obscene_vect.transform(comment1)
load_obscene.predict_proba(comment1_vect)[:,1]

array([0.67372253])

In [32]:
comment2_vect = load_obscene_vect.transform(comment2)
load_obscene.predict_proba(comment2_vect)[:,1]

array([0.37810652])

# For threat

In [33]:
comment1_vect = load_threat_vect.transform(comment1)
load_threat.predict_proba(comment1_vect)[:,1]

array([0.92])

In [34]:
comment2_vect = load_threat_vect.transform(comment2)
load_threat.predict_proba(comment2_vect)[:,1]

array([0.01])

# For Insult

In [35]:
comment1_vect = load_insult_vect.transform(comment1)
load_insult.predict_proba(comment1_vect)[:,1]

array([0.54025105])

In [36]:
comment2_vect = load_insult_vect.transform(comment2)
load_insult.predict_proba(comment2_vect)[:,1]

array([0.25984177])

# For Identity hate

In [37]:
comment1_vect = load_identity_hate_vect.transform(comment1)
load_identity_hate.predict_proba(comment1_vect)[:,1]

array([0.24343337])

In [38]:
comment2_vect = load_identity_hate_vect.transform(comment2)
load_identity_hate.predict_proba(comment2_vect)[:,1]

array([0.21687379])